### ISSUE TITLE
map_sample with transiting object

### ISSUE THREAD

**Issue by florian-lienhard** [kima-org/kima#19]
Hi João, 

Thank you for the new version. The map_sample function works well if I don't set a transiting planet. If set one, however, I get this error message (when I run map_sample):

model = RVmodel(fix=True, npmax=Np, data=data)
model.set_transiting_planet(1)
[...]
model.TR_Tcprior = [kima.distributions.Gaussian(T0, T0_err)]
[...]
kima.run(model, steps=nsteps)
res = kima.load_results(model)
res.map_sample()
<img width="912" alt="Screenshot 2024-07-16 at 15 13 19" src="https://github.com/user-attachments/assets/3980d034-5344-4408-9a3e-4714881896f4">

Do you know what's going on here?

**Comment by j-faria** [comment]
Hi Florian,

It should be fixed now, in [v6.1.0](https://pypi.org/project/kima/6.1.0/) that I just uploaded to PyPI.
Can you try running `pip install kima -U` and checking the plot again?

**Comment by florian-lienhard** [comment]
This worked. Thank you very much!
